/**
 * Static mock data for all dashboard views.
 * Replace with real API calls when connecting to the backend.
 */

export const tasks = [
  {
    id: "task-001",
    title: "Test a mobile checkout flow",
    detail: "Open the provided mobile checkout prototype, add one product and complete the delivery details. Note any confusing language, blocked steps, or visual issues. Submit two screenshots and a short written summary.",
    buyer: "Nova Commerce",
    buyerEmail: "nova@example.com",
    reward: 85,
    workers: 40,
    requiredWorkers: 18,
    deadline: "Sep 12, 2026",
    category: "UX Testing",
    submissionInfo: "Include screenshots of the delivery and payment steps. Written feedback should be at least 80 characters.",
    imageUrl: "",
    status: "active",
  },
  {
    id: "task-002",
    title: "Rate 50 product descriptions",
    detail: "Read each product description and rate clarity, accuracy, and appeal on a 1–5 scale. Submit the completed spreadsheet.",
    buyer: "StyleHub",
    buyerEmail: "stylehub@example.com",
    reward: 120,
    workers: 25,
    requiredWorkers: 12,
    deadline: "Sep 18, 2026",
    category: "Research",
    submissionInfo: "Upload the completed rating spreadsheet.",
    imageUrl: "",
    status: "active",
  },
  {
    id: "task-003",
    title: "Transcribe a 10-minute interview",
    detail: "Listen to the provided audio file and transcribe the full conversation. Format the transcript with speaker labels and timestamps every 30 seconds.",
    buyer: "MediaSync",
    buyerEmail: "mediasync@example.com",
    reward: 200,
    workers: 10,
    requiredWorkers: 5,
    deadline: "Sep 15, 2026",
    category: "Transcription",
    submissionInfo: "Submit a .docx or .txt file with the full transcript.",
    imageUrl: "",
    status: "active",
  },
  {
    id: "task-004",
    title: "Sign up and complete onboarding",
    detail: "Create an account on the provided web app, complete the full onboarding flow, and provide feedback on each step.",
    buyer: "FinTrack",
    buyerEmail: "fintrack@example.com",
    reward: 65,
    workers: 60,
    requiredWorkers: 30,
    deadline: "Sep 20, 2026",
    category: "UX Testing",
    submissionInfo: "Screenshot of each onboarding step and written feedback.",
    imageUrl: "",
    status: "active",
  },
  {
    id: "task-005",
    title: "Survey: Remote work preferences",
    detail: "Complete a 15-question survey about your remote work habits, tools, and preferences. Estimated 5 minutes.",
    buyer: "WorkPulse",
    buyerEmail: "workpulse@example.com",
    reward: 30,
    workers: 200,
    requiredWorkers: 140,
    deadline: "Sep 25, 2026",
    category: "Survey",
    submissionInfo: "Complete the survey in full. Partial submissions will not be accepted.",
    imageUrl: "",
    status: "active",
  },
  {
    id: "task-006",
    title: "Verify local business listings",
    detail: "Check 20 business listings for accuracy of name, address, phone number, and hours of operation.",
    buyer: "MapVerify",
    buyerEmail: "mapverify@example.com",
    reward: 95,
    workers: 30,
    requiredWorkers: 8,
    deadline: "Sep 14, 2026",
    category: "Research",
    submissionInfo: "Submit a spreadsheet with corrections noted for each listing.",
    imageUrl: "",
    status: "paused",
  },
];

export const submissions = [
  {
    id: "sub-001",
    taskId: "task-001",
    taskTitle: "Test a mobile checkout flow",
    workerName: "Maya Chen",
    workerEmail: "maya@example.com",
    buyerName: "Nova Commerce",
    buyerEmail: "nova@example.com",
    payableAmount: 85,
    submissionDetails: "Completed all requested steps. The delivery address validation was clear, but the payment button moved below the fold on a smaller screen.",
    date: "Sep 6, 2026",
    status: "pending",
  },
  {
    id: "sub-002",
    taskId: "task-002",
    taskTitle: "Rate 50 product descriptions",
    workerName: "Daniel Okafor",
    workerEmail: "daniel@example.com",
    buyerName: "StyleHub",
    buyerEmail: "stylehub@example.com",
    payableAmount: 120,
    submissionDetails: "All 50 descriptions rated and annotated with specific improvement notes.",
    date: "Sep 5, 2026",
    status: "approved",
  },
  {
    id: "sub-003",
    taskId: "task-003",
    taskTitle: "Transcribe a 10-minute interview",
    workerName: "Sofia Martins",
    workerEmail: "sofia@example.com",
    buyerName: "MediaSync",
    buyerEmail: "mediasync@example.com",
    payableAmount: 200,
    submissionDetails: "Full transcript with speaker labels and timestamps at 30-second intervals.",
    date: "Sep 4, 2026",
    status: "approved",
  },
  {
    id: "sub-004",
    taskId: "task-004",
    taskTitle: "Sign up and complete onboarding",
    workerName: "Ethan Park",
    workerEmail: "ethan@example.com",
    buyerName: "FinTrack",
    buyerEmail: "fintrack@example.com",
    payableAmount: 65,
    submissionDetails: "Completed all steps but the email verification took too long.",
    date: "Sep 3, 2026",
    status: "rejected",
  },
  {
    id: "sub-005",
    taskId: "task-001",
    taskTitle: "Test a mobile checkout flow",
    workerName: "Nora Blake",
    workerEmail: "nora@example.com",
    buyerName: "Nova Commerce",
    buyerEmail: "nova@example.com",
    payableAmount: 85,
    submissionDetails: "The checkout worked smoothly. I found the address step clear, but the main payment action became difficult to see at 320px width.",
    date: "Sep 2, 2026",
    status: "approved",
  },
];

export const transactions = [
  { id: "TXN-38471", item: "500 coins", amount: "$20.00", date: "Sep 5, 2026", status: "Completed" },
  { id: "TXN-38290", item: "1,000 coins", amount: "$35.00", date: "Aug 28, 2026", status: "Completed" },
  { id: "TXN-37812", item: "150 coins", amount: "$10.00", date: "Aug 15, 2026", status: "Completed" },
  { id: "TXN-37411", item: "500 coins", amount: "$20.00", date: "Jul 30, 2026", status: "Completed" },
  { id: "TXN-36990", item: "10 coins", amount: "$1.00", date: "Jul 12, 2026", status: "Completed" },
];

export const users = [
  { name: "Maya Chen", email: "maya.chen@example.com", role: "worker", coins: 1680, photo: "" },
  { name: "Daniel Okafor", email: "daniel.okafor@example.com", role: "worker", coins: 2520, photo: "" },
  { name: "Nora Blake", email: "nora.blake@example.com", role: "buyer", coins: 3360, photo: "" },
  { name: "Samuel Lee", email: "samuel.lee@example.com", role: "worker", coins: 4200, photo: "" },
  { name: "Priya Shah", email: "priya.shah@example.com", role: "admin", coins: 5040, photo: "" },
];

export const withdrawals = [
  { worker: "Maya Chen", email: "maya@example.com", coins: 800, amount: "$40.00", method: "PayPal", account: "m•••@mail.com", date: "Sep 6, 2026", status: "pending" },
  { worker: "Daniel Okafor", email: "daniel@example.com", coins: 1200, amount: "$60.00", method: "Bank transfer", account: "•••• 4912", date: "Sep 5, 2026", status: "pending" },
  { worker: "Sofia Martins", email: "sofia@example.com", coins: 500, amount: "$25.00", method: "PayPal", account: "s•••@mail.com", date: "Sep 4, 2026", status: "pending" },
  { worker: "Ethan Park", email: "ethan@example.com", coins: 950, amount: "$47.50", method: "Bank transfer", account: "•••• 7831", date: "Sep 3, 2026", status: "pending" },
];

export const chartData = [
  { month: "Apr", value: 280 },
  { month: "May", value: 390 },
  { month: "Jun", value: 340 },
  { month: "Jul", value: 520 },
  { month: "Aug", value: 610 },
  { month: "Sep", value: 760 },
];

export const notificationItems = [
  { type: "success", title: "Submission approved", text: "You earned 85 coins", time: "2m" },
  { type: "danger", title: "Submission rejected", text: "Proof needs more detail", time: "1h" },
  { type: "success", title: "Withdrawal approved", text: "$42.00 is on the way", time: "Yesterday" },
];

/** Coin pricing packages */
export const coinPackages = [
  { coins: 10, price: 1 },
  { coins: 150, price: 10 },
  { coins: 500, price: 20, popular: true },
  { coins: 1000, price: 35 },
];
